### ISSUE TITLE
Adicionar scripts que estão no HTML para uma pasta JS

### ISSUE THREAD

**Issue by meiii15** [meiii15/portfoliomei#2]

**Comment by PedroXSQueiroz** [comment]
Criei a pasta "js" e criei três arquivos:
- text-type.js: responsável pela parte da animação de digitção
- na-nar.js: responsável pelo barra lateral de menu
- index.js: responsavel por instaciar os objetos os outros arquivos

Também ajustei um pouco a identação do código e a na organização das "classes"
